---
title: "ECON_7201

APPLIED ECONOMETRICS

ASSIGNMENT 1"
format: pdf
editor: visual
---

# 1 GIT AND GIT HUB

I have created the repository and pushed all the changes to my repository on github.com (https://github.com/Emmanuel-spec493/econ_3201)

# 2 LATEX

(a) *E*(Y) = $y_{1}$$p_{1}$ +... +$y_{k}$$p_{k}$ = $\sum_{i=1}^k$ $y_{i}$$p_{i}$

(b) $\sigma_{y}$ =Var(Y) =E\[(Y-$\mu_{y})^2$\] =$\sum_{i=1}^k$$(y_{i}$ - $\mu_{y})^2$$p_{i}$

(c) $\hat{\beta}$ =$\frac{\sum_{i=1}^n(y - y_{i})(x-x_{i})}{\sum_{i=1}^n(x -x_{i })^2}$

(d) P($a\leq Y\leq b$) = $\int_{a}^b$ fY (*y*)*dy*

(e) $\hat{g}$(x) = $\frac{\frac{1}{nh}\sum_{i=1}^ny_{i}k(\frac{x_{i}-x}{h})}{\frac{1}{nh}\sum_{i=1}^nk(\frac{x_{i}-x}{h})}$

# 3.1 R

(a) n \<- 1000

    k \<- n/2

(b) u1 \<- runif(k, min = 0, max = 1)

    u2 \<- runif(k, min =0, max = 1)

(c)z1 \<- sqrt(-2*log(u1))* cos(2*pi*u2)

```         
   z2 <- sqrt(-2*log(u1))* sin(2*pi*u2)
   

 z <- c(z1,z2) 
```
  mean (x)




 read.csv("hlthexp.csv")
 
 
 # 3.2 
 
 (a)  There is no missing values for Hospitals .
 
      sum(is.na(df$Hospitals))
[1] 0


df$TotalOtherServices <- df$"Other.Professionals..Dental.Services"  +     
 df$"Other.Professionals..Vision.Care.Services" +  df$"Total.Other.Professionals"   
 
 df<-data.frame(df,"Prescription Drugs")
df <- data.frame(df, Prescription.Drugs = $Prescribed.Drugs)

df$Hospitals[df$Year == 1983]
df[df$Year %in% 2012:2022, ]

mpg <- ggplot2 ::mpg
mpg_2008 <- subset(mpg, year == 2008)
min(mpg_2008$cty, na.rm = TRUE)


